name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build iOS app
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        env:
          USER_CREATION_TOKEN: ${{ secrets.USER_CREATION_TOKEN }}
        run: |
          xcodebuild build \
            -scheme "MyMangas" \
            -project MyMangas.xcodeproj \
            -destination "generic/platform=iOS" \
            CODE_SIGN_IDENTITY=- \
            AD_HOC_CODE_SIGNING_ALLOWED=YES
            USER_CREATION_TOKEN=$USER_CREATION_TOKEN