name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Setup build environment
        run: |
          sudo mkdir -p /Volumes/workspace/repository
          sudo mkdir -p /Volumes/workspace/DerivedData
          sudo mkdir -p /Volumes/workspace/tmp
          sudo chown -R $USER /Volumes/workspace
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: /Volumes/workspace/repository

      - name: Create and verify Config file
        env:
          USER_CREATION_TOKEN: ${{ secrets.USER_CREATION_TOKEN }}
        run: |
          cd /Volumes/workspace/repository
          echo "USER_CREATION_TOKEN = $USER_CREATION_TOKEN" > Config.xcconfig
          
          # Verify file exists and has content
          if [ -f "Config.xcconfig" ]; then
            echo "Config file created successfully"
            ls -la Config.xcconfig
            cat Config.xcconfig
          else
            echo "Error: Config file was not created"
            exit 1
          fi
          
          chmod 644 Config.xcconfig
          
          echo "Project structure:"
          ls -la

      - name: Build
        env:
          scheme: "MyMangas"
        run: |
          cd /Volumes/workspace/repository
          
          xcodebuild build \
            -scheme "$scheme" \
            -project MyMangas.xcodeproj \
            -destination "generic/platform=iOS" \
            -derivedDataPath /Volumes/workspace/DerivedData \
            -resultBundleVersion 3 \
            -resultBundlePath /Volumes/workspace/resultbundle.xcresult \
            -resultStreamPath /Volumes/workspace/tmp/resultBundleStream.json \
            -IDEPostProgressNotifications=YES \
            CODE_SIGN_IDENTITY=- \
            AD_HOC_CODE_SIGNING_ALLOWED=YES \
            COMPILER_INDEX_STORE_ENABLE=NO \
            -hideShellScriptEnvironment